In [1]:
import pandas as pd

In [20]:
import pandas as pd

df = pd.read_csv( r"C:\Users\Dell\Downloads\messy_employee_dataset_1000_rows (1).csv")
df

,user_id,age,salary,department,join_date,city,performance_score,experience_years,is_active
0,user_0,-5,₹50000,HR,2020/12/01,DELHI,3,five,True
1,U1001,30,45000,Finance,15/02/2021,Delhi,3,1,yes
2,U1002,30,25000,HR,NaN,Delhi,excellent,10,False
3,NaN,unknown,NaN,HR,invalid,Hyderabad,excellent,5,yes
4,NaN,NaN,120000.75,IT,NaN,DELHI,NaN,-1,False
...,...,...,...,...,...,...,...,...,...
995,NaN,60,₹50000,HR,15/02/2021,DELHI,2,five,NaN
996,U1996,NaN,NaN,IT,15/02/2021,Mumbai,NaN,5,no
997,user_997,unknown,25000,HR,invalid,Mumbai,3,5,True
998,U1998,-5,25000,NaN,15/02/2021,Bangalore,1,0,True
999,NaN,30,45000,HR,2022-01-15,Hyderabad,excellent,five,no

In [14]:
df = pd.read_csv( r"C:\Users\Dell\Downloads\messy_employee_dataset_1000_rows (1).csv")
df

,user_id,age,salary,department,join_date,city,performance_score,experience_years,is_active
0,user_0,-5,₹50000,HR,2020/12/01,DELHI,3,five,True
1,U1001,30,45000,Finance,15/02/2021,Delhi,3,1,yes
2,U1002,30,25000,HR,NaN,Delhi,excellent,10,False
3,NaN,unknown,NaN,HR,invalid,Hyderabad,excellent,5,yes
4,NaN,NaN,120000.75,IT,NaN,DELHI,NaN,-1,False
...,...,...,...,...,...,...,...,...,...
995,NaN,60,₹50000,HR,15/02/2021,DELHI,2,five,NaN
996,U1996,NaN,NaN,IT,15/02/2021,Mumbai,NaN,5,no
997,user_997,unknown,25000,HR,invalid,Mumbai,3,5,True
998,U1998,-5,25000,NaN,15/02/2021,Bangalore,1,0,True
999,NaN,30,45000,HR,2022-01-15,Hyderabad,excellent,five,no

In [35]:
df.shape

(491, 10)

In [36]:
df.columns

Index(['user_id', 'age', 'salary', 'department', 'join_date', 'city',
       'performance_score', 'experience_years', 'is_active', 'joining_year'],
      dtype='object')

In [38]:
#2.calculate percentage of missing values for each column
df.isnull().sum()
df_missing = (df.isnull().sum() / len(df)) * 100


print(df_missing)

df.dtypes
mixed_columns = []

for col in df.columns:
    types = df[col].dropna().apply(type).unique()
    
    if len(types) > 1:
        mixed_columns.append(col)

print("Columns with mixed datatypes:")
print(mixed_columns)
df

df.apply(lambda col: col.map(type).nunique())

user_id               0.203666
age                  48.268839
salary               40.122200
department           13.238289
join_date            78.004073
city                 14.052953
performance_score    10.183299
experience_years     38.900204
is_active            18.533605
joining_year         78.004073
dtype: float64
Columns with mixed datatypes:
[]

user_id              2
age                  1
salary               1
department           2
join_date            2
city                 2
performance_score    2
experience_years     1
is_active            2
joining_year         1
dtype: int64

In [39]:
#4clean user id by replacing empty strings with nan and converting into uppercase
df['user_id'] = df['user_id'].replace('', pd.NA).str.upper()
df['user_id']

C:\Users\Dell\AppData\Local\Temp\ipykernel_19276\3469738734.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['user_id'] = df['user_id'].replace('', pd.NA).str.upper()

0        USER_0
1         U1001
2         U1002
3           NaN
5        USER_5
         ...
990       U1990
991       U1991
996       U1996
997    USER_997
998       U1998
Name: user_id, Length: 491, dtype: object

In [40]:
#5 convert age to numeric and replace invalid values(negative or >100) with nan
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df.loc[(df['age'] < 0) | (df['age'] > 100), 'age'] = pd.NA
df

C:\Users\Dell\AppData\Local\Temp\ipykernel_19276\3347971636.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age'] = pd.to_numeric(df['age'], errors='coerce')

,user_id,age,salary,department,join_date,city,performance_score,experience_years,is_active,joining_year
0,USER_0,NaN,NaN,HR,2020-12-01,Delhi,3,NaN,True,2020.0
1,U1001,30.0,45000.0,FINANCE,NaT,Delhi,3,1.0,True,NaN
2,U1002,30.0,25000.0,HR,NaT,Delhi,excellent,10.0,False,NaN
3,NaN,NaN,NaN,HR,NaT,Hyderabad,excellent,5.0,True,NaN
5,USER_5,NaN,25000.0,IT,NaT,NaN,3,0.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...
990,U1990,NaN,NaN,SALES,NaT,Hyderabad,NaN,NaN,False,NaN
991,U1991,45.0,NaN,HR,NaT,Mumbai,NaN,NaN,True,NaN
996,U1996,NaN,NaN,IT,NaT,Mumbai,NaN,5.0,False,NaN
997,USER_997,NaN,25000.0,HR,NaT,Mumbai,3,5.0,True,NaN
998,U1998,NaN,25000.0,NaN,NaT,Bangalore,1,0.0,True,NaN

In [41]:
# 6 clean salary by removing currency symbols and converting it to numeric
df['salary'] = df['salary'].replace('[\$,]', '', regex=True)
df['salary'] = pd.to_numeric(df['salary'], errors='coerce')
df['salary']

C:\Users\Dell\AppData\Local\Temp\ipykernel_19276\349805391.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['salary'] = df['salary'].replace('[\$,]', '', regex=True)
C:\Users\Dell\AppData\Local\Temp\ipykernel_19276\349805391.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['salary'] = pd.to_numeric(df['salary'], errors='coerce')

0          NaN
1      45000.0
2      25000.0
3          NaN
5      25000.0
        ...
990        NaN
991        NaN
996        NaN
997    25000.0
998    25000.0
Name: salary, Length: 491, dtype: float64

In [42]:
#7 convert join date into datetime format handling multiple date formats
df['join_date'] = pd.to_datetime(df['join_date'], errors='coerce', infer_datetime_format=True)
df["joining_year"] = df["join_date"].dt.year
df['join_date']

C:\Users\Dell\AppData\Local\Temp\ipykernel_19276\2833963448.py:2: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df['join_date'] = pd.to_datetime(df['join_date'], errors='coerce', infer_datetime_format=True)
C:\Users\Dell\AppData\Local\Temp\ipykernel_19276\2833963448.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['join_date'] = pd.to_datetime(df['join_date'], errors='coerce', infer_datetime_format=True)
C:\Users\Dell\AppData\Local\Temp\ipykernel_19276\2833963448.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["joining_year"] = df["join_date"].dt.year

0     2020-12-01
1            NaT
2            NaT
3            NaT
5            NaT
         ...
990          NaT
991          NaT
996          NaT
997          NaT
998          NaT
Name: join_date, Length: 491, dtype: datetime64[ns]

In [43]:
# 8 extract joining year from the cleaned join_date column
df["joining_year"] = df["join_date"].dt.year
df["joining_year"]

C:\Users\Dell\AppData\Local\Temp\ipykernel_19276\4242447604.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["joining_year"] = df["join_date"].dt.year

0      2020.0
1         NaN
2         NaN
3         NaN
5         NaN
        ...
990       NaN
991       NaN
996       NaN
997       NaN
998       NaN
Name: joining_year, Length: 491, dtype: float64

In [44]:
#9 standardize department values by trimming spaces and converting to uppercase
df['department'] = df['department'].str.strip().str.upper()
df['department']

C:\Users\Dell\AppData\Local\Temp\ipykernel_19276\3389524542.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['department'] = df['department'].str.strip().str.upper()

0           HR
1      FINANCE
2           HR
3           HR
5           IT
        ...
990      SALES
991         HR
996         IT
997         HR
998        NaN
Name: department, Length: 491, dtype: object

In [45]:
#10 normalize city names to a consistent case and spelling
df['city'] = df['city'].str.strip().str.title()
df['city']

C:\Users\Dell\AppData\Local\Temp\ipykernel_19276\3020617169.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city'] = df['city'].str.strip().str.title()

0          Delhi
1          Delhi
2          Delhi
3      Hyderabad
5            NaN
         ...
990    Hyderabad
991       Mumbai
996       Mumbai
997       Mumbai
998    Bangalore
Name: city, Length: 491, dtype: object

In [46]:
#11 convert performance score into numeric by mapping text values to numbers
performance_mapping = {
    'Excellent': 3,
    'Good': 2,
    'Poor': 1
}

df['performance_score'] = df['performance_score'].map(performance_mapping)
df['performance_score'] = pd.to_numeric(df['performance_score'], errors='coerce')
df['performance_score']

C:\Users\Dell\AppData\Local\Temp\ipykernel_19276\739549949.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['performance_score'] = df['performance_score'].map(performance_mapping)
C:\Users\Dell\AppData\Local\Temp\ipykernel_19276\739549949.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['performance_score'] = pd.to_numeric(df['performance_score'], errors='coerce')

0     NaN
1     NaN
2     NaN
3     NaN
5     NaN
       ..
990   NaN
991   NaN
996   NaN
997   NaN
998   NaN
Name: performance_score, Length: 491, dtype: float64

In [47]:
 #12 clean experience years by converting text values to numeric and removing negatives
df['experience_years'] = pd.to_numeric(df['experience_years'], errors='coerce')
df.loc[df['experience_years'] < 0, 'experience_years'] = pd.NA
df['experience_years']

C:\Users\Dell\AppData\Local\Temp\ipykernel_19276\890852720.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['experience_years'] = pd.to_numeric(df['experience_years'], errors='coerce')

0       NaN
1       1.0
2      10.0
3       5.0
5       0.0
       ...
990     NaN
991     NaN
996     5.0
997     5.0
998     0.0
Name: experience_years, Length: 491, dtype: float64

In [49]:
#14 identify and remove duplicate records based on user_id
df = df.drop_duplicates(subset=['user_id'])
df

,user_id,age,salary,department,join_date,city,performance_score,experience_years,is_active,joining_year
0,USER_0,NaN,NaN,HR,2020-12-01,Delhi,NaN,NaN,True,2020.0
1,U1001,30.0,45000.0,FINANCE,NaT,Delhi,NaN,1.0,True,NaN
2,U1002,30.0,25000.0,HR,NaT,Delhi,NaN,10.0,False,NaN
3,NaN,NaN,NaN,HR,NaT,Hyderabad,NaN,5.0,True,NaN
5,USER_5,NaN,25000.0,IT,NaT,NaN,NaN,0.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...
990,U1990,NaN,NaN,SALES,NaT,Hyderabad,NaN,NaN,False,NaN
991,U1991,45.0,NaN,HR,NaT,Mumbai,NaN,NaN,True,NaN
996,U1996,NaN,NaN,IT,NaT,Mumbai,NaN,5.0,False,NaN
997,USER_997,NaN,25000.0,HR,NaT,Mumbai,NaN,5.0,True,NaN
998,U1998,NaN,25000.0,NaN,NaT,Bangalore,NaN,0.0,True,NaN

In [50]:
#15 create a clean final dataframe containing only valid, standardized records
clean_df = df.dropna(subset=['user_id', 'age', 'salary', 'join_date', 'department', 'city', 'performance_score', 'experience_years', 'is_active'])
clean_df.reset_index(drop=True, inplace=True)
clean_df
clean_df.info()
clean_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            0 non-null      object
 1   age                0 non-null      float64
 2   salary             0 non-null      float64
 3   department         0 non-null      object
 4   join_date          0 non-null      datetime64[ns]
 5   city               0 non-null      object
 6   performance_score  0 non-null      float64
 7   experience_years   0 non-null      float64
 8   is_active          0 non-null      object
 9   joining_year       0 non-null      float64
dtypes: datetime64[ns](1), float64(5), object(4)
memory usage: 132.0+ bytes

Empty DataFrame
Columns: [user_id, age, salary, department, join_date, city, performance_score, experience_years, is_active, joining_year]
Index: []

In [ ]:
#13.to convert is active values
import pandas as pd

# Standardize is_active column
df["is_active"] = (
    df["is_active"]
    .astype(str)
    .str.strip()
    .str.lower()
    .map({
        "true": True,
        "yes": True,
        "false": False,
        "no": False
    })
)

In [57]:
df[["is_active"]].head()

  is_active
0      True
1      True
2     False
3      True
5     False

In [58]:
print(df["is_active"])

0       True
1       True
2      False
3       True
5      False
       ...
990    False
991     True
996    False
997     True
998     True
Name: is_active, Length: 491, dtype: object

In [59]:
df.head()

,user_id,age,salary,department,join_date,city,performance_score,experience_years,is_active,joining_year
0,USER_0,NaN,NaN,HR,2020-12-01,Delhi,NaN,NaN,True,2020.0
1,U1001,30.0,45000.0,FINANCE,NaT,Delhi,NaN,1.0,True,NaN
2,U1002,30.0,25000.0,HR,NaT,Delhi,NaN,10.0,False,NaN
3,NaN,NaN,NaN,HR,NaT,Hyderabad,NaN,5.0,True,NaN
5,USER_5,NaN,25000.0,IT,NaT,NaN,NaN,0.0,False,NaN

In [60]:
df["is_active"].unique()

array([True, False, nan], dtype=object)